### PR TITLE
Add avro support

### PR DESCRIPTION
**Pull request by kumaranvpl**

### CODE REVIEW

**Review by davorrunje — APPROVED** [review]

**Comment by passuied** [comment]
@davorrunje is this change available in faststream or just in fastkafka? It looks like it's for faststream but when I look at the changed files it looks like fastkafka... I cannot find any avro support on faststream main branch as well

**Comment by davorrunje** [comment]
@passuied custom decoders/encoders are supported in FastStream as explained here: https://faststream.airt.ai/0.2/getting-started/serialization/

Let me know if this is clear. If not, I'll write an Avro example in the docs.

**Comment by davorrunje** [comment]
@passuied we create an issue for adding an example to docs, should be finished this week https://github.com/airtai/faststream/issues/843

**Comment by davorrunje** [comment]
> @davorrunje is this change available in faststream or just in fastkafka? It looks like it's for faststream but when I look at the changed files it looks like fastkafka... I cannot find any avro support on faststream main branch as well

@passuied we added an Avro example in docs: https://faststream.airt.ai/0.2/getting-started/serialization/examples/#avro

**Comment by passuied** [comment]
Thanks. Any plans to support schema registry?

**Comment by davorrunje** [comment]
@passuied Not yet, but please create an issue for any feature you are interested in and it will get prioritized as a community request. We implement features largely based on feedback we get.

**Comment by thuibr** [comment]
@passuied  #964 issue addresses the schema registry

**Pull request merged**
